config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

	namespace :casein do
		resources :faqs do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :dashboards

		resources :documents do
      collection do
        post :insert_file
        post :edit_multiple
        post :update_multiple
      end
    end
		resources :news_items do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :courseformats do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :menus do
      collection do
        post :edit_multiple
        post :update_multiple
      end
    end
		resources :quotes do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :fees do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :events do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :pages do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :staffs do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :photos do
      collection do
        get :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :klasses do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :courses do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
	end

  post "casein/versions/:id/revert" => 'casein/versions#revert', :as => "revert_version"
  post 'whats_next/:type/:salutation/:name/:campaign/:opp_uid', :to => 'static_pages#whats_next', :as => "whats_next"
  get 'tersm_and_conditions', :to => 'static_pages#terms_and_conditions'
  get 'privacy_policy', :to => 'static_pages#privacy_policy'
  post 'get_calendar', :to => 'static_pages#get_calendar'
  get 'speciality/:speciality', :to => 'staffs#index', as: :speciality
  get 'contact', :to => 'static_pages#contact'
  post 'send_contact', :to => 'static_pages#send_contact'

  resources :courseformats, :only => [:index, :show] do
      resource :photos, :only => [:index, :show]
  end

  resources :courses, :only => [:index, :show] do
      resource :photos, :only => [:index, :show]
  end

  resources :staffs, :only => [:index, :show]

  resources :pages, :only => [:index, :show]

  resources :events, :only => [:index, :show]

  resources :news_items, :only => [:index, :show]

  resources :bookings, :only => [:index, :show, :create, :edit] do
    collection do
      get :payment
      post :whats_next
      post :charge
      get :confirm_payment
    end
  end

  resources :faqs, :only => [:index, :show, :create]

end

app/models/page.rb
class Page < ActiveRecord::Base
	extend FriendlyId
	mount_uploader :feature_image, ImageUploader
	# before_save :falsify_all_others
	has_ancestry
	
	belongs_to :user
	friendly_id :title, use: :slugged
	has_paper_trail :on => [:update, :create, :destroy]
	scope :published_now, -> { self.with_published_state.where('published_at <= ?', Time.zone.now)}
	has_many :menus, as: :navigation, :dependent => :destroy
	has_many :recordfies
	has_many :courses, through: :recordfies, source: :entriable, source_type: 'Course'
	has_many :courseformats, through: :recordfies, source: :entriable, source_type: 'Courseformat'
	has_many :events, through: :recordfies, source: :entriable, source_type: 'Event'
	has_many :fees, through: :recordfies, source: :entriable, source_type: 'Fee'
	has_many :klasses, through: :recordfies, source: :entriable, source_type: 'Klass'
	has_many :quotes, through: :recordfies, source: :entriable, source_type: 'Quote'
	has_many :staffs, through: :recordfies, source: :entriable, source_type: 'Staff'
	
	acts_as_xlsx
	acts_as_taggable_on :keywords

	include Workflow

	workflow do
		state :draft do
			event :submit, transition_to: :pending_review
			event :approve, transition_to: :approved
			event :publish, transition_to: :published
		end

		state :pending_review do
			event :approve, transition_to: :approved
			event :reject, transition_to: :draft
			event :publish, transition_to: :published
		end

		state :approved do
			event :publish, transition_to: :published
			event :submit, transition_to: :pending_review
			event :reject, transition_to: :draft
		end

		state :published do
			event :unpublish, transition_to: :draft
		end
	end

	def self.states
		workflow_spec.state_names
	end

	def publish
		update_attribute(:published_at, Time.zone.now) if self.published_at.nil?
	end

	def unpublish
		update_attribute(:published_at, nil)
	end

	# def falsify_all_others
	# 	self.class.where('id != ? AND feature').update_all("feature = 'false'")
	# end

	def self.to_csv
		CSV.generate do |csv|
			csv << column_names
			all.each do |item|
				csv << item.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			item = find_by_id(row["id"]) || new
			item.attributes = row.to_hash.slice(*self.column_names)
			item.save!
		end
	end
end

app/controllers/casein/courseformats_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class CourseformatsController < Casein::CaseinController
    before_filter :load_courseformat, :only => [:show, :update, :destroy]
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Course formats'
      @courseformats = Courseformat.rank(:row_order)
      respond_to do |format|
        format.html
        format.csv { send_data @courseformats.to_csv, filename: "courseformats-#{Date.today}.csv"}
        format.xlsx
      end
    end

    def import
      Courseformat.import(params[:file])
      expire_fragment("footer")
      expire_fragment("header")
      flash[:notice] = 'File has been imported'
      redirect_to casein_courseformats_path
    end
  
    def show
      @casein_page_title = 'View course format'
      @photos = Photo.all
      @photo = Photo.new
      @courseformat.highlights.build
      @pages = @courseformat.pages
    end
  
    def new
      @casein_page_title = 'Add a new course format'
      @courseformat = Courseformat.new
      @photo = @courseformat.photos.build
      3.times { @courseformat.highlights.build }
    end

    def create
      @courseformat = Courseformat.new courseformat_params
    
      if @courseformat.save
        expire_fragment("footer")
        expire_fragment("header")
        if params[:publish]
            @courseformat.publish!
        end
        if params[:photos_attributes]
          params[:photos_attributes]['image'].each do |image|
            @courseformat.photos.create(image: image)
          end
        end
        flash[:notice] = 'Course format created'
        redirect_to casein_courseformats_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new course format'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update course format'
      
      respond_to do |format|
        if @courseformat.update_attributes courseformat_params
          if params[:submit]  
            @courseformat.submit!
          elsif params[:approve]
            @courseformat.approve!
          elsif params[:reject]
            @courseformat.reject!
          elsif params[:publish]
            @courseformat.publish!
          elsif params[:unpublish]
            @courseformat.unpublish!
          end
          expire_fragment("footer")
          expire_fragment("header")
          format.html { redirect_to casein_courseformat_path(@courseformat), notice: "Course Format has been updated. #{undo_link}" }
          format.js
        else
          flash.now[:warning] = 'There were problems when trying to update this course format'
          render :action => :show
        end
     end
    end
    
    def edit_multiple
      @courseformats = Courseformat.where(id: courseformat_params[:courseformat_ids])

      if params[:edit]
        render "courseformats/edit_multiple"
      elsif params[:unpublish]
        @courseformats.each do |courseformat|
          courseformat.unpublish! if courseformat.published?
        end
        redirect_to casein_courseformats_path
      elsif params[:publish]
        @courseformats.each do |courseformat|
          courseformat.publish! if !courseformat.published?
        end
          redirect_to casein_courseformats_path
      elsif params[:delete]
          @courseformats.destroy_all
          redirect_to casein_courseformats_path
      end
    end

    def update_multiple
     @courseformats = Courseformat.friendly.update(params[:courseformats].keys, params[:courseformats].values)
      expire_fragment("footer")
      expire_fragment("header")
      @courseformats.reject! { |courseformat| courseformat.errors.empty? }

      if @courseformats.empty?
        redirect_to casein_courseformats_path
      else
        render "courseformats/edit_multiple"
      end
    end
 
    def destroy

      @courseformat.destroy
      # @courseformat.photos.each do |photo|
      #   photo.update_attributes(imageable_id: nil, imageable_type: nil)
      # end
      expire_fragment("footer")
      expire_fragment("header")
      flash[:notice] = "Course format has been deleted. #{undo_link}"
      redirect_to casein_courseformats_path
    end
  
    private
      
      def courseformat_params
        params.require(:courseformat).permit(:title, :description, :courseformats, :feature, :published_at, {:page_ids => []}, {:courseformat_ids => []}, :file,
          :workflow_state, :whats_new, :when_from, :when_to, :venue, :address1, :row_order_position, :address2, :city, :county, :country, :post_code, :keyword_list,
          photos_attributes: [:id, :caption, :image], highlights_attributes: [:id, :title, :description, :_destroy])
      end
      
      def undo_link
        view_context.link_to("undo", revert_version_path(@courseformat.versions.last), :method => :post).html_safe
      end
      
      def load_courseformat
        @courseformat ||= Courseformat.friendly.find params[:id]
      end
  
  end
end

app/controllers/casein/courses_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class CoursesController < Casein::CaseinController
    before_filter :load_course, :only => [:show, :update, :destroy]
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Courses'
  		@courses = Course.rank(:row_order)
      respond_to do |format|
        format.html
        format.csv { send_data @courses.to_csv, filename: "courses-#{Date.today}.csv"}
        format.xlsx
      end
    end


    def import
      Course.import(params[:file])
      expire_fragment("footer")
      expire_fragment("header")
      flash[:notice] = 'File has been imported'
      redirect_to casein_courses_path
    end
  
    def show
      @casein_page_title = 'View course'
      @photos = Photo.all
      @photo = Photo.new
    end
  
    def new
      @casein_page_title = 'Add a new course'
    	@course = Course.new
      @photo = @course.photos.build
    end

    def create
      @course = Course.new course_params
    
      if @course.save
        expire_fragment("footer")
        expire_fragment("header")
          if params[:publish]
            @course.publish!
          end
          if params[:photos_attributes]
            params[:photos_attributes]['image'].each do |image|
              @course.photos.create(image: image)
            end
          end
        flash[:notice] = 'Course created'
        redirect_to casein_courses_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new course'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update course'
            
      respond_to do |format|

      if @course.update_attributes course_params
          if params[:submit]
            @course.submit!
          elsif params[:approve]
            @course.approve!
          elsif params[:reject]
            @course.reject!
          elsif params[:publish]
            @course.publish!
          elsif params[:unpublish]
            @course.unpublish!
          end
          expire_fragment("footer")
          expire_fragment("header")
          format.html { redirect_to casein_course_path(@course), notice: "Course has been updated. #{undo_link}" }
          format.js
        else
          flash.now[:warning] = 'There were problems when trying to update this course'
          render :action => :show
        end
     end
    end

    def edit_multiple
      @courses = Course.where(id: course_params[:course_ids])

      if params[:edit]
        render "courses/edit_multiple"
      elsif params[:unpublish]
        @courses.each do |course|
          course.unpublish! if course.published?
        end
        redirect_to casein_courses_path
      elsif params[:publish]
        @courses.each do |course|
          course.publish! if !course.published?
        end
          redirect_to casein_courses_path
      elsif params[:delete]
          @courses.destroy_all
          redirect_to casein_courses_path
      end
    end

    def update_multiple
     @courses = Course.friendly.update(params[:courses].keys, params[:courses].values)
      expire_fragment("footer")
      expire_fragment("header")
      @courses.reject! { |course| course.errors.empty? }
      if @courses.empty?
        redirect_to casein_courses_path
      else
        render "courses/edit_multiple"
      end
    end

    def destroy
      @course.destroy
      # @course.photos.each do |photo|
      #   photo.update_attributes(imageable_id: nil, imageable_type: nil)
      # end
      expire_fragment("footer")
      expire_fragment("header")
      flash[:notice] = "Course has been deleted. #{undo_link}"
      redirect_to casein_courses_path
    end
  
    private
      
      def course_params
        params.require(:course).permit(:title, :courses, :workflow_state, 
          :row_order_position, {:course_ids => []}, :feature, :keyword_list, :courseformat_id,
          :bookable, :description, :published_at, photos_attributes: [:id, :caption, :course_id, :image])
      end

      def undo_link
        view_context.link_to("undo", revert_version_path(@course.versions.last), :method => :post).html_safe
      end

      def load_course
        @course ||= Course.friendly.find params[:id]      
      end

  end
end

app/controllers/casein/drafts_controller.rb
class Casein::DraftsController < ApplicationController


	def update
		@draft = Draftsman::Draft.find(params[:id])
		@draft.publish!
		flash[:success] = 'The draft was published successfully.'
      	redirect_to admin_drafts_path
	end
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'AIMS International Music School'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'AIMS_red-sm.jpg'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://aims-international.herokuapp.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@aims.uk.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      # url_for :controller => :casein, :action => :blank
      casein_dashboards_path
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom casein/dropzone jquery-ui font-awesome froala_style.min froala_editor.min plugins/code_view.min 
        plugins/image.min plugins/image_manager.min plugins/fullscreen.min plugins/colors.min plugins/char_counter.min plugins/file.min]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom casein/dropzone jquery-ui froala_editor.min plugins/image.min plugins/image_manager.min plugins/code_view.min 
        plugins/paragraph_format.min plugins/paragraph_style.min plugins/fullscreen.min plugins/link.min plugins/colors.min plugins/font_size.min plugins/align.min
        plugins/char_counter.min plugins/quote.min plugins/file.min plugins/lists.min]
    end
  end
end

app/helpers/casein/drafts_helper.rb
module Casein::DraftsHelper
end

app/helpers/casein/versions_helper.rb
module Casein::VersionsHelper
end

app/views/casein/klasses/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->


<div class="row">
	<div class="col-lg-6 col-md-6">
		<%= casein_text_field f, f.object, :title, placeholder: "Opera Arias" %>
	</div>
		<div class="col-lg-6 col-md-6">
		<%= casein_date_field f, f.object, :published_at, casein_label: "Publish date" %>
	</div>
</div>
<div class="row">
	<div class="col-lg-12 col-md-12">
		<%= casein_text_area f, f.object, :description, :class => 'description-box' %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6 col-md-6">
		<%= casein_text_area f, f.object, :repertoire, :class => 'description-box' %>
	</div>
	<div class="col-lg-6 col-md-6">
		<%= casein_text_field f, f.object, :number_of_sessions  %>
	</div>
	<div class="col-lg-6 col-md-6">
		<%= casein_select f, f.object, :session_of_day, Klass::SESSIONS, include_blank: true %>
	</div>
	<div class="col-lg-6 col-md-6">
		<%= casein_collection_select f, f.object, :klass, :course_id, Course.all, :id, :title, include_blank: true %>
	</div>
</div>

app/views/casein/klasses/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<table class="table table-striped table-hover table-condensed sortable-table">
	<thead>
		<tr>
			<th><%= check_box_tag 'multi' %></th>
			<th><%= casein_sort_link "Title", :title %></th>
			<th><%= casein_sort_link "# of sessions", :number_of_sessions %></th>
			<th><%= casein_sort_link "Session of day", :session_of_day %></th>
			<th><%= casein_sort_link "Course", :course_title %></th>
			<th><%= casein_sort_link "Publish Date", :published_at %></th>
			<th><%= casein_sort_link "Updated at", :updated_at %></th>
			<th><%= casein_sort_link "Status", :workflow_state %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
		<% klasses.each do |klass| %>
			<tr data-update-url=<%= casein_klass_path(klass) %>>
				<td><%= check_box_tag 'klass[klass_ids][]', klass.id, checked = false, { id: dom_id(klass), :class => 'index-check' } %>
				</td>
				<td><%= casein_table_cell_link klass.title, casein_klass_path(klass) %></td>
				<td><%= casein_table_cell_link klass.number_of_sessions, casein_klass_path(klass) %></td>
				<td><%= casein_table_cell_link klass.session_of_day, casein_klass_path(klass) %></td>
				<td><%= casein_table_cell_link klass.course.title, casein_klass_path(klass) if klass.course.present? %></td>
				<td><%= casein_table_cell_link d_m_y(klass.published_at), casein_klass_path(klass) %></td>	
				<td><%= casein_table_cell_link d_m_y(klass.updated_at), casein_klass_path(klass) %></td>
				<td><%= link_to casein_klass_path(klass) do %>
					<%= image_tag state_icon(klass.workflow_state) %>
					<% end %>
				</td>
				<td class="delete">
					<%= link_to(casein_show_row_icon("trash"), casein_klass_path(klass), :method => :delete, :data => { :confirm => "Are you sure you want to delete this klass?" }) %>
				</td>
			</tr>
		<% end %>				
</table>

<script>
	var fixHelper = function(e, ui) {
		ui.children().each(function() {
			$(this).width($(this).width());
		});
		return ui;
	};
	$(function() {
		$('.sortable-table tbody').sortable({
			helper: fixHelper,
			update: function(event, ui) {
				$.ajax({
					type: 'PUT',
					url: ui.item.data('update-url'),
					dataType: 'json',
					data: { klass: {row_order_position: ui.item.index()}}
				});
			}
		});
	});
</script>

app/views/casein/klasses/edit_multiple.html.erb
<h2>Klasses</h2>

<%= form_tag update_multiple_casein_klasses_path, defaults: { input_html: { :class => 'multiple-edit' } } do %>	
	<table class="table table-striped table-hover table-condensed edit-mulitple">
		<thead>
			<tr>
				<th><%= casein_sort_link "Title", :title %></th>
				<th><%= casein_sort_link "# of sessions", :number_of_sessions %></th>
				<th><%= casein_sort_link "Session of day", :session_of_day %></th>
				<th><%= casein_sort_link "Course", :course_title %></th>
				<th><%= casein_sort_link "Publish Date", :published_at %></th>
				<th><%= casein_sort_link "Status", :workflow_state %></th>
			</tr>
		</thead>

			<% @klasses.each do |klass| %>
				<%= simple_fields_for "klasses[]", klass do |f| %> 
				<tr>
					<td><%= casein_table_cell_link klass.title, casein_klass_path(klass) %></td>
					<td><%= f.input :number_of_sessions, label: false %></td>
					<td><%= f.input :session_of_day, label: false, collection: Klass::SESSIONS, include_blank: true %></td>
					<td><%= f.input :course_id, collection: Course.all, label: false,text_method: :title %></td>
					<td><%= f.input :published_at, as: :date, html5: true, label: false  %></td>
					<td><%= f.input :workflow_state, label: false, :collection => Klass.states %></td>
				</tr>
				<% end %>
			<% end %>			
	</table>
	<p class="submits">
		<%= link_to 'Cancel', casein_klasses_path, :class => 'btn btn-mini btn-default' %>
	<%= submit_tag "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>
<% end %>	

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new klass".html_safe, new_casein_klass_path %></li>

<% end %>

app/views/casein/klasses/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Klasses</h2>
<%= form_tag edit_multiple_casein_klasses_path, method: :post do %>

	<%= render :partial => 'casein/klasses/table', :locals => { :klasses => @klasses } %>
	<%= render :partial => 'casein/layouts/multi_btns' %>
	
<% end %>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new klass".html_safe, new_casein_klass_path %></li>
	Download Data: <%= link_to 'CSV', casein_klasses_path(format: 'csv') %> | 
	<%= link_to 'Excel', casein_klasses_path(format: 'xlsx') %>
	<br />
	<br />
	Import Data with CSV file:
	<br />
	<%= form_tag import_casein_klasses_path, multipart: true do %>
		<%= file_field_tag :file, accept: 'text/csv' %>
		<%= submit_tag "Import", :class => 'btn btn-xs btn-primary pull-right' %>
	<% end %>
<% end %>

app/views/casein/klasses/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Add a new klass</h2>

<%= form_for @klass, :url => casein_klasses_path, html: {multipart: true} do |f| %>
	
	<%= render :partial => 'casein/klasses/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_klasses_path, :class => 'btn btn-mini btn-default' %>
		<%= f.submit "Add new klass", :class => "btn btn-mini btn-primary" %>
		<% if current_user.is_admin? %>
			<%= submit_tag "Publish", name: 'publish', :class => 'btn btn-mini btn-primary' %>
		<% end %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_klasses_path %></li>
<% end %>

app/views/casein/klasses/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Klass</h2>

<%= form_for @klass, :url => casein_klass_path(@klass) do |f| %>

	<%= render :partial => 'casein/klasses/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_courses_path, :class => 'btn btn-mini btn-default' %>
		<%= render :partial => 'casein/layouts/approval_q_buttons', :locals => { :f => f } %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_klasses_path %></li>
	<%= simple_form_for @klass, :url => casein_klass_path(@klass), html: {:id => 'stateform'}, remote: true do |f| %>
		<%= render partial: 'casein/layouts/status_form', :locals => {:f => f, :record => @klass } %>
	<% end %>
<% end %>

app/views/casein/klasses/update.js.erb
$('#stateform select').hide();
$('#state-status').show();
$('#icon-span').append("<%= j image_tag state_icon(@klass.workflow_state), :class => 'state-icon' %>");
$('#current-state').html('<%= j @klass.current_state.to_s %>');
var currentState = $('#current-state').text();
$('#update-date').html('<%= j @klass.updated_at.to_s %>');
buttonChange();