config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

	namespace :casein do
		resources :faqs do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :dashboards

		resources :documents do
      collection do
        post :insert_file
        post :edit_multiple
        post :update_multiple
      end
    end
		resources :news_items do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :courseformats do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :menus do
      collection do
        post :edit_multiple
        post :update_multiple
      end
    end
		resources :quotes do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :fees do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :events do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :pages do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :staffs do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :photos do
      collection do
        get :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :klasses do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
		resources :courses do
      collection do
        post :edit_multiple
        post :update_multiple
        post :import
      end
    end
	end

  post "casein/versions/:id/revert" => 'casein/versions#revert', :as => "revert_version"
  post 'whats_next/:type/:salutation/:name/:campaign/:opp_uid', :to => 'static_pages#whats_next', :as => "whats_next"
  get 'tersm_and_conditions', :to => 'static_pages#terms_and_conditions'
  get 'privacy_policy', :to => 'static_pages#privacy_policy'
  post 'get_calendar', :to => 'static_pages#get_calendar'
  get 'speciality/:speciality', :to => 'staffs#index', as: :speciality
  get 'contact', :to => 'static_pages#contact'
  post 'send_contact', :to => 'static_pages#send_contact'

  resources :courseformats, :only => [:index, :show] do
      resource :photos, :only => [:index, :show]
  end

  resources :courses, :only => [:index, :show] do
      resource :photos, :only => [:index, :show]
  end

  resources :staffs, :only => [:index, :show]

  resources :pages, :only => [:index, :show]

  resources :events, :only => [:index, :show]

  resources :news_items, :only => [:index, :show]

  resources :bookings, :only => [:index, :show, :create, :edit] do
    collection do
      get :payment
      post :whats_next
      post :charge
      get :confirm_payment
    end
  end

  resources :faqs, :only => [:index, :show, :create]

end

app/models/fee.rb
class Fee < ActiveRecord::Base
	belongs_to :courseformat
	has_paper_trail :on => [:update, :create, :destroy]
	
	scope :published_now, -> { self.with_published_state.where('published_at <= ?', Time.zone.now)}
	scope :event, -> {where(fee_type: 'Event')}
	has_many :recordfies, as: :entriable
	has_many :pages, through: :recordfies
	
	acts_as_xlsx
	
	include Workflow

	workflow do
		state :draft do
			event :submit, transition_to: :pending_review
			event :approve, transition_to: :approved
			event :publish, transition_to: :published
		end

		state :pending_review do
			event :approve, transition_to: :approved
			event :reject, transition_to: :draft
			event :publish, transition_to: :published
		end

		state :approved do
			event :publish, transition_to: :published
			event :submit, transition_to: :pending_review
			event :reject, transition_to: :draft
		end

		state :published do
			event :unpublish, transition_to: :draft
		end
	end
	
	def full_description
		"#{self.fee_type} #{self.category}: #{self.description}, £#{self.amount}" 
	end
	
	def self.states
		workflow_spec.state_names
	end

	def publish
		update_attribute(:published_at, Time.zone.now) if self.published_at.nil?
	end

	def unpublish
		update_attribute(:published_at, nil)
	end

	def title
		"#{self.fee_type}, #{self.category}"
	end

	def self.to_csv
		CSV.generate do |csv|
			csv << column_names
			all.each do |item|
				csv << item.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			item = find_by_id(row["id"]) || new
			item.attributes = row.to_hash.slice(*self.column_names)
			item.save!
		end
	end
end

app/models/page.rb
class Page < ActiveRecord::Base
	extend FriendlyId
	mount_uploader :feature_image, ImageUploader
	# before_save :falsify_all_others
	has_ancestry
	
	belongs_to :user
	friendly_id :title, use: :slugged
	has_paper_trail :on => [:update, :create, :destroy]
	scope :published_now, -> { self.with_published_state.where('published_at <= ?', Time.zone.now)}
	has_many :menus, as: :navigation, :dependent => :destroy
	has_many :recordfies
	has_many :courses, through: :recordfies, source: :entriable, source_type: 'Course'
	has_many :courseformats, through: :recordfies, source: :entriable, source_type: 'Courseformat'
	has_many :events, through: :recordfies, source: :entriable, source_type: 'Event'
	has_many :fees, through: :recordfies, source: :entriable, source_type: 'Fee'
	has_many :klasses, through: :recordfies, source: :entriable, source_type: 'Klass'
	has_many :quotes, through: :recordfies, source: :entriable, source_type: 'Quote'
	has_many :staffs, through: :recordfies, source: :entriable, source_type: 'Staff'
	
	acts_as_xlsx
	acts_as_taggable_on :keywords

	include Workflow

	workflow do
		state :draft do
			event :submit, transition_to: :pending_review
			event :approve, transition_to: :approved
			event :publish, transition_to: :published
		end

		state :pending_review do
			event :approve, transition_to: :approved
			event :reject, transition_to: :draft
			event :publish, transition_to: :published
		end

		state :approved do
			event :publish, transition_to: :published
			event :submit, transition_to: :pending_review
			event :reject, transition_to: :draft
		end

		state :published do
			event :unpublish, transition_to: :draft
		end
	end

	def self.states
		workflow_spec.state_names
	end

	def publish
		update_attribute(:published_at, Time.zone.now) if self.published_at.nil?
	end

	def unpublish
		update_attribute(:published_at, nil)
	end

	# def falsify_all_others
	# 	self.class.where('id != ? AND feature').update_all("feature = 'false'")
	# end

	def self.to_csv
		CSV.generate do |csv|
			csv << column_names
			all.each do |item|
				csv << item.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			item = find_by_id(row["id"]) || new
			item.attributes = row.to_hash.slice(*self.column_names)
			item.save!
		end
	end
end

app/controllers/casein/courseformats_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class CourseformatsController < Casein::CaseinController
    before_filter :load_courseformat, :only => [:show, :update, :destroy]
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Course formats'
      @courseformats = Courseformat.rank(:row_order)
      respond_to do |format|
        format.html
        format.csv { send_data @courseformats.to_csv, filename: "courseformats-#{Date.today}.csv"}
        format.xlsx
      end
    end

    def import
      Courseformat.import(params[:file])
      expire_fragment("footer")
      expire_fragment("header")
      flash[:notice] = 'File has been imported'
      redirect_to casein_courseformats_path
    end
  
    def show
      @casein_page_title = 'View course format'
      @photos = Photo.all
      @photo = Photo.new
      @courseformat.highlights.build
      @pages = @courseformat.pages
    end
  
    def new
      @casein_page_title = 'Add a new course format'
      @courseformat = Courseformat.new
      @photo = @courseformat.photos.build
      3.times { @courseformat.highlights.build }
    end

    def create
      @courseformat = Courseformat.new courseformat_params
    
      if @courseformat.save
        expire_fragment("footer")
        expire_fragment("header")
        if params[:publish]
            @courseformat.publish!
        end
        if params[:photos_attributes]
          params[:photos_attributes]['image'].each do |image|
            @courseformat.photos.create(image: image)
          end
        end
        flash[:notice] = 'Course format created'
        redirect_to casein_courseformats_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new course format'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update course format'
      
      respond_to do |format|
        if @courseformat.update_attributes courseformat_params
          if params[:submit]  
            @courseformat.submit!
          elsif params[:approve]
            @courseformat.approve!
          elsif params[:reject]
            @courseformat.reject!
          elsif params[:publish]
            @courseformat.publish!
          elsif params[:unpublish]
            @courseformat.unpublish!
          end
          expire_fragment("footer")
          expire_fragment("header")
          format.html { redirect_to casein_courseformat_path(@courseformat), notice: "Course Format has been updated. #{undo_link}" }
          format.js
        else
          flash.now[:warning] = 'There were problems when trying to update this course format'
          render :action => :show
        end
     end
    end
    
    def edit_multiple
      @courseformats = Courseformat.where(id: courseformat_params[:courseformat_ids])

      if params[:edit]
        render "courseformats/edit_multiple"
      elsif params[:unpublish]
        @courseformats.each do |courseformat|
          courseformat.unpublish! if courseformat.published?
        end
        redirect_to casein_courseformats_path
      elsif params[:publish]
        @courseformats.each do |courseformat|
          courseformat.publish! if !courseformat.published?
        end
          redirect_to casein_courseformats_path
      elsif params[:delete]
          @courseformats.destroy_all
          redirect_to casein_courseformats_path
      end
    end

    def update_multiple
     @courseformats = Courseformat.friendly.update(params[:courseformats].keys, params[:courseformats].values)
      expire_fragment("footer")
      expire_fragment("header")
      @courseformats.reject! { |courseformat| courseformat.errors.empty? }

      if @courseformats.empty?
        redirect_to casein_courseformats_path
      else
        render "courseformats/edit_multiple"
      end
    end
 
    def destroy

      @courseformat.destroy
      # @courseformat.photos.each do |photo|
      #   photo.update_attributes(imageable_id: nil, imageable_type: nil)
      # end
      expire_fragment("footer")
      expire_fragment("header")
      flash[:notice] = "Course format has been deleted. #{undo_link}"
      redirect_to casein_courseformats_path
    end
  
    private
      
      def courseformat_params
        params.require(:courseformat).permit(:title, :description, :courseformats, :feature, :published_at, {:page_ids => []}, {:courseformat_ids => []}, :file,
          :workflow_state, :whats_new, :when_from, :when_to, :venue, :address1, :row_order_position, :address2, :city, :county, :country, :post_code, :keyword_list,
          photos_attributes: [:id, :caption, :image], highlights_attributes: [:id, :title, :description, :_destroy])
      end
      
      def undo_link
        view_context.link_to("undo", revert_version_path(@courseformat.versions.last), :method => :post).html_safe
      end
      
      def load_courseformat
        @courseformat ||= Courseformat.friendly.find params[:id]
      end
  
  end
end

app/controllers/casein/dashboards_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class DashboardsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Dashboards'


      # ga_client  = Google::APIClient.new

      # ga_client.authorization = Signet::OAuth2::Client.new(
      #   :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
      #   :audience             => 'https://accounts.google.com/o/oauth2/token',
      #   :scope                => 'https://www.googleapis.com/auth/analytics.readonly',
      #   :issuer               => ENV['client_email'],
      #   :application_name     => 'aims-website',
      #   :application_version  => '0.0.0.0',
      #   :signing_key          => Google::APIClient::PKCS12.load_key(ENV['P12_CONTENT'], 'notasecret')
      # ).tap { |auth| auth.fetch_access_token! }

      # api_method = ga_client.discovered_api('analytics','v3').data.ga.get


      # make queries
      @period = '30'
      # @results = ga_client.execute(:api_method => api_method, :parameters => {
      #   'ids'        => 'ga:78025227',
      #   'start-date' => "#{@period}daysAgo",
      #   'end-date'   => Date.today.to_s,
      #   'dimension'  => 'ga:date',
      #   'metrics'    => 'ga:users,ga:newUsers,ga:sessions,ga:avgSessionDuration,ga:pageviews,ga:uniquePageviews,ga:pageviewsPerSession,ga:timeOnPage'
      # })
      # ,ga:city,ga:mobileDeviceModel,ga:country,ga:mobileDeviceBranding
      # puts result.data.rows.inspect
    end
  
   
  
    private
      
      def dashboard_params
        params.require(:dashboard).permit(:index)
      end
  
  
  end
end

app/controllers/casein/drafts_controller.rb
class Casein::DraftsController < ApplicationController


	def update
		@draft = Draftsman::Draft.find(params[:id])
		@draft.publish!
		flash[:success] = 'The draft was published successfully.'
      	redirect_to admin_drafts_path
	end
end

app/controllers/casein/versions_controller.rb
class Casein::VersionsController < ApplicationController

	def revert
	  @version = PaperTrail::Version.find(params[:id])
	  if @version.reify
	    @version.reify.save!
	  else
	    @version.item.destroy
	  end
	  link_name = params[:redo] == "true" ? "undo" : "redo"
	  link = view_context.link_to(link_name, revert_version_path(@version.next, :redo => !params[:redo]), :method => :post)
	  redirect_to :back, :notice => "Undid #{@version.event}. #{link}"
	end
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'AIMS International Music School'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'AIMS_red-sm.jpg'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://aims-international.herokuapp.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@aims.uk.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      # url_for :controller => :casein, :action => :blank
      casein_dashboards_path
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom casein/dropzone jquery-ui font-awesome froala_style.min froala_editor.min plugins/code_view.min 
        plugins/image.min plugins/image_manager.min plugins/fullscreen.min plugins/colors.min plugins/char_counter.min plugins/file.min]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom casein/dropzone jquery-ui froala_editor.min plugins/image.min plugins/image_manager.min plugins/code_view.min 
        plugins/paragraph_format.min plugins/paragraph_style.min plugins/fullscreen.min plugins/link.min plugins/colors.min plugins/font_size.min plugins/align.min
        plugins/char_counter.min plugins/quote.min plugins/file.min plugins/lists.min]
    end
  end
end

app/helpers/casein/drafts_helper.rb
module Casein::DraftsHelper
end

app/helpers/casein/versions_helper.rb
module Casein::VersionsHelper
end

app/views/casein/pages/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->


<div class="row">
	<div class="col-lg-6 col-md-6">
		<%= casein_text_field f, f.object, :title %>
	</div>
	<div class="col-lg-5 col-md-5">
		<%= casein_date_field f, f.object, :published_at, casein_label: "Publish date" %>
	</div>
	<div class="col-lg-1 col-md-1 feature_page_check">
		<%= casein_check_box f, f.object, :feature %>
	</div>
</div>
<div class = 'row'>
	<div class="col-lg-6 col-md-6">
		<%= casein_text_field f, f.object, :keyword_list, casein_label: "Keywords (separated by commas)", value: f.object.keyword_list.to_s, id: 'keywords', data: {autocomplete_source: ActsAsTaggableOn::Tag.all.map(&:name)} %>
	</div>
	<div class="col-lg-6 col-md-6">
		<%= casein_collection_select f, f.object, :page, :parent_id, @pages, :id, :title, casein_label: "Parent page", include_blank: true %>
	</div>
</div>
<div class="row">
	<div class="col-lg-12 col-md-12">
		<%= casein_text_area f, f.object, :content, :class => 'description-box' %>
	</div>
</div>
<div class="row">
	<% if @page.feature_image.present? %>

			<div class="col-lg-6 col-md-6">
				<%= image_tag @page.feature_image_url(:thumb).to_s, :class => 'thumbnail img-responsive' %>
			</div>

			<div class="col-lg-6 col-md-6">
				<%= casein_file_field f, f.object, :page, :feature_image %>
			</div>

	<% else %>

			<div class="col-lg-6 col-md-6">		
				<%= casein_file_field f, f.object, :page, :feature_image %>
			</div>

	<% end %>
</div>

app/views/casein/pages/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= check_box_tag 'multi' %></th>
			<th><%= casein_sort_link "Title", :title %></th>
			<th><%= casein_sort_link "Content", :content %></th>
			<th><%= casein_sort_link "Parent", :parent %></th>
			<th><%= casein_sort_link "Feature", :feature %></th>
			<th><%= casein_sort_link "Publish Date", :published_at %></th>
			<th><%= casein_sort_link "Updated at", :updated_at %></th>
			<th><%= casein_sort_link "Status", :workflow_state %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% pages.each do |page| %>
		<tr>
			<td><%= check_box_tag 'page[page_ids][]', page.id, checked = false, { id: dom_id(page), :class => 'index-check' } %>
				</td>
			<td><%= casein_table_cell_link page.title, casein_page_path(page) %></td>
			<td><%= casein_table_cell_link page.content, casein_page_path(page), :casein_truncate => 100 %></td>
			<td><%= casein_table_cell_link page.parent.title, casein_page_path(page) if page.parent.present? %></td>
			<td><%= link_to casein_page_path(page) do %>
			<%= image_tag 'check.png', :class=>'true-check img-responsive' if page.feature %>
			<% end %></td>
			<td><%= casein_table_cell_link d_m_y(page.published_at), casein_page_path(page) %></td>	
			<td><%= casein_table_cell_link d_m_y(page.updated_at), casein_page_path(page) %></td>
			<td><%= link_to casein_page_path(page) do %>
					<%= image_tag state_icon(page.workflow_state) %>
					<% end %>
				</td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_page_path(page), :method => :delete, :data => { :confirm => "Are you sure you want to delete this page?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/pages/edit_multiple.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->
<h2>Pages</h2>
<%= form_tag update_multiple_casein_pages_path, defaults: { input_html: { :class => 'multiple-edit' } } do %>

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Title", :title %></th>
			<th><%= casein_sort_link "Parent", :parent %></th>
			<th><%= casein_sort_link "Feature", :feature %></th>
			<th><%= casein_sort_link "Publish Date", :published_at %></th>
			<th><%= casein_sort_link "Status", :workflow_state %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% @pages.each do |page| %>
		<%= simple_fields_for "pages[]", page do |f| %> 
		<tr>
			<td><%= casein_table_cell_link page.title, casein_page_path(page) %></td>
			<td><%= f.input :parent_id, collection: Page.published_now.order(:title), label: false %></td>
			<td><%= f.input :published_at, as: :date, html5: true, label: false  %></td>
			<td><%= f.input :feature, label: false %></td>
			<td><%= f.input :workflow_state, label: false, :collection => Page.states %>
					</td>
				</td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_page_path(page), :method => :delete, :data => { :confirm => "Are you sure you want to delete this page?" }) %>
			</td>
		</tr>
		<% end %>
	<% end %>
</table>

<p class="submits">
		<%= link_to 'Cancel', casein_pages_path, :class => 'btn btn-mini btn-default' %>
	<%= submit_tag "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>
<% end %>	

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new klass".html_safe, new_casein_klass_path %></li>

<% end %>

app/views/casein/pages/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Pages</h2>
<%= form_tag edit_multiple_casein_pages_path, method: :post do %>

	<%= render :partial => 'casein/pages/table', :locals => { :pages => @pages } %>

	<%= render :partial => 'casein/layouts/multi_btns' %>
<% end %>


<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new page".html_safe, new_casein_page_path %></li>
	Download Data: <%= link_to 'CSV', casein_pages_path(format: 'csv') %> | 
	<%= link_to 'Excel', casein_pages_path(format: 'xlsx') %>
	<br />
	<br />
	Import Data with CSV file:
	<br />
	<%= form_tag import_casein_pages_path, multipart: true do %>
		<%= file_field_tag :file, accept: 'text/csv' %>
		<%= submit_tag "Import", :class => 'btn btn-xs btn-primary pull-right' %>
	<% end %>
<% end %>

app/views/casein/pages/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Add a new page</h2>

<%= form_for @page, :url => casein_pages_path, html: {multipart: true} do |f| %>
	
	<%= render :partial => 'casein/pages/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_pages_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new page", :class => "btn btn-mini btn-primary" %>
		<% if current_user.is_admin? %>
			<%= submit_tag "Publish", name: 'publish', :class => 'btn btn-mini btn-primary' %>
		<% end %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_pages_path %></li>
<% end %>

app/views/casein/pages/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Page</h2>

<%= form_for @page, :url => casein_page_path(@page) do |f| %>

	<%= render :partial => 'casein/pages/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_events_path, :class => 'btn btn-mini btn-default' %>
		<%= render :partial => 'casein/layouts/approval_q_buttons', :locals => { :f => f } %>
	</p>

<% end %>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Existing Records to Page</h4>
      </div>
      <%= simple_form_for @page, :url => casein_page_path(@page) do |f| %>
	      <div class="modal-body">
	      			<div class='record'>
						<span class='record-title'>Course Formats</span>(<%= link_to 'select all', '#', :class => 'multi-record' %>)<br />
						<%= f.collection_check_boxes :courseformat_ids, @courseformats, :id, :title %>
					</div>
	      			<div class='record'>
						<span class='record-title'>Courses</span>(<%= link_to 'select all', '#', :class => 'multi-record' %>)<br />
						<%= f.collection_check_boxes :course_ids, @courses, :id, :title %>
					</div>
					<div class='record'>
						<span class='record-title'>Fees</span>(<%= link_to 'select all', '#', :class => 'multi-record' %>)<br />
						<%= f.collection_check_boxes :fee_ids, @fees, :id, :title %>
					</div>
					<div class='record'>
						<span class='record-title'>Events</span>(<%= link_to 'select all', '#', :class => 'multi-record' %>)<br />
						<%= f.collection_check_boxes :event_ids, @events, :id, :title %>
					</div>
					<div class='record'>
						<span class='record-title'>Quotes</span>(<%= link_to 'select all', '#', :class => 'multi-record' %>)<br />
						<%= f.collection_check_boxes :quote_ids, @quotes, :id, :saying %>
					</div>
					<div class='record'>
						<span class='record-title'>Staffs</span>(<%= link_to 'select all', '#', :class => 'multi-record' %>)<br />
						<%= f.collection_check_boxes :staff_ids, @staffs, :id, :full_name %>
		  			</div>
		   </div>
		   <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		        <%= f.submit 'Edit records', :class => 'btn btn-mini btn-primary' %>
		   </div>
    	<% end %>
    </div>
  </div>
</div>




<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_pages_path %></li>
	<li><%= link_to "#{casein_show_icon "plus-sign"}Add records".html_safe, '#', data: { toggle: 'modal', target: '#myModal'} %></li>
	<%= simple_form_for @page, :url => casein_page_path(@page), html: {:id => 'stateform'}, remote: true do |f| %>
		<%= render partial: 'casein/layouts/status_form', :locals => {:f => f, :record => @page } %>
	<% end %>
<% end %>

app/views/casein/pages/update.js.erb
$('#stateform select').hide();
$('#state-status').show();
$('#icon-span').append("<%= j image_tag state_icon(@page.workflow_state), :class => 'state-icon' %>");
$('#current-state').html('<%= j @page.current_state.to_s %>');
var currentState = $('#current-state').text();
$('#update-date').html('<%= j @page.updated_at.to_s %>');
buttonChange();